import type { NextConfig } from "next";
import path from "node:path";

const nextConfig: NextConfig = {
  // Static export — required for hosting on R2 / S3 / any static bucket.
  // `out/` is generated by `next build` and uploaded as-is.
  output: "export",
  // Image Optimization API is a server feature; static hosts can't run it.
  // Each <Image> becomes a plain <img>; size hints still help LCP.
  images: { unoptimized: true },
  // R2 / S3 serve directories as `/path/index.html`. trailingSlash ensures
  // every internal link resolves cleanly without a redirect dance.
  trailingSlash: true,
  // Pin workspace root so Next does not walk up to stray package.json files
  // in parent directories (a common one lives at ~/package.json from an
  // accidental `npm install` in the home dir). Without this, the CSS pipeline
  // resolves `@import "tailwindcss"` from the wrong dir, fails, and retries
  // every HMR tick — feels like a memory leak.
  //
  // `turbopack.root` covers `next dev` (Turbopack is default in Next 16).
  // `outputFileTracingRoot` covers `next build` / webpack-side tracing.
  turbopack: {
    root: path.join(__dirname),
  },
  outputFileTracingRoot: path.join(__dirname),
};

export default nextConfig;
